[general]
import = ["~/repos/autoarch/dotfiles/alacritty/dracula.toml",
    "~/repos/autoarch/dotfiles/alacritty/common.toml",
    "~/repos/autoarch/dotfiles/alacritty/linux.toml",
    "C:\\Users\\ProblemBot\\AppData\\Roaming\\alacritty\\common.toml",
    "C:\\Users\\ProblemBot\\AppData\\Roaming\\alacritty\\dracula.toml",
    "C:\\Users\\ProblemBot\\AppData\\Roaming\\alacritty\\windows.toml"
]
