[general]
live_config_reload = true
import = ["C:\\Users\\ProblemBot\\Appdata\\Roaming\\alacritty\\dracula.toml", ]

[terminal]
shell = { program = "C:\\Windows\\System32\\wsl.exe", args = ["-d Ubuntu --cd ~",] }

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[keyboard]
bindings = [
    { key = "Return", mods = "Alt", action = "ReceiveChar" },
]
