#!/bin/bash

# If not running interactively, don't do anything
# [[ $- != *i* ]] && return

[[ -f $HOME/repos/autoarch/bash/alias ]] && . $HOME/repos/autoarch/bash/alias
[[ -f $HOME/repos/autoarch/bash/env ]] && . $HOME/repos/autoarch/bash/env

# PS1='[\u@\h \W]\$ '

# Sets up nvm and it's directory in the bash environment
export NVM_DIR="$HOME/.nvm"
[[ -f $HOME/repos/autoarch/bash/nvm ]] && . $HOME/repos/autoarch/bash/nvm

export HISTFILESIZE=0

#--Check if Oh-My-Posh is installed and run it
if type -P oh-my-posh &> /dev/null; then
	eval "$(oh-my-posh init bash --config $HOME/repos/autoarch/dotfiles/oh-my-posh/froczh.omp.json)"
else
	echo "Error: Oh-My-Posh not installed."
fi

#--Check if fzf and bat installed
if type -P fzf &> /dev/null; then
	eval "$(fzf --version)"
else
	echo "Error: FZF not installed."
fi
