#!/bin/bash

# If not running interactively, don't do anything
# [[ $- != *i* ]] && return

[[ -f $HOME/autoarch/bash/alias ]] && . $HOME/autoarch/bash/alias
[[ -f $HOME/autoarch/bash/env ]] && . $HOME/autoarch/bash/env
[[ -f /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion

PS1='[\u@\h \W]\$ '

# Sets up nvm and it's directory in the bash environment
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export HISTFILESIZE=0

clear
#--Check if neofetch is installed and run it
if [ -z "$TERMINAL_LAUNCHED" ]; then
    TERMINAL_LAUNCHED=true
    if type -P neofetch &> /dev/null; then
        if [ -z "$TMUX" ]; then
            neofetch
        fi
    else
        echo "Error: NeoFetch not installed."
    fi
fi

#--Check if Oh-My-Posh is installed and run it
if type -P oh-my-posh &> /dev/null; then
	eval "$(oh-my-posh init bash --config /home/fsb/autoarch/dotfiles/oh-my-posh/custom.omp.json)"
else
	echo "Error: Oh-My-Posh not installed."
fi

#--Check if fzf and bat installed
if type -P fzf &> /dev/null; then
	eval "$(fzf --bash)"
else
	echo "Error: FZF not installed."
fi
